name: APK Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # En güncel checkout sürümü

      - name: Buildozer Action
        uses: ArtemSerebrennukov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Hata veren v2 yerine en güncel v4
        with:
          name: İhale-Radar-Paketi
          path: bin/*.apk
