name: APK Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Dosya kontrolü (Hata 100'ü çözmek için)
          ls -R
          if [ ! -f main.py ]; then
            echo "HATA: Ana dizinde main.py dosyası bulunamadı!"
            exit 1
          fi
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          # Otomatik onay ve derleme
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ihale-Radar-APK
          path: bin/*.apk
